---
fixtures:
  repositories:
    epel: https://github.com/voxpupuli/puppet-epel.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
